name: Manage core infrastructure resources

on:
  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: Terraform action
        required: true
        options:
          - apply-plan
          - apply
          - destroy-plan
          - destroy
        default: apply-plan
      environment:
        type: environment
        description: The targeted GitHub environment
        required: false
        default: test

jobs:
  call-reusable-workflow:
    name: Reuseable manage resources ${{inputs.action}}
    uses: .github/workflows/reuseable-core.yml
    with:
      action: ${{inputs.action}}
      environment: ${{inputs.environment}}
      iac_version: ${{github.ref_name}}
    secrets: inherit
