name: Manage cloud resources

on:
  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: Terraform action
        required: true
        options:
          - apply-plan
          - apply
          - destroy-plan
          - destroy
        default: apply-plan
      environment:
        type: environment
        description: The targeted GitHub environment
        required: false
        default: test

jobs:
  manage-resources:
    name: Manage resources
    uses: keeonline/github-workflows/.github/workflows/terraform-action.yml@v0.0.4
    with:
      action: ${{inputs.action}}
      repo_owner: ${{github.repository_owner}}
      repo_name: ${{github.event.repository.name}}
      work_dir: terraform/core
      environment: ${{inputs.environment}}
      iac_ref: ${{github.ref_name}}
    secrets: inherit
    permissions:
      contents: write
      id-token: write
