name: Manage infrastructure

on:
  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: Terraform action
        required: true
        options:
          - apply-plan
          - apply
          - destroy-plan
          - destroy
        default: apply-plan
      environment:
        type: environment
        description: The targeted GitHub environment
        required: false
        default: test

jobs:
  manage-resources:
    name: Manage resources
    runs-on: ubuntu-24.04
    environment: ${{inputs.environment}}
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Get the artefact version values
        id: versions
        uses: keeonline/github-actions/artefact-version@karate

      - name: show versions
        run: |
          echo "current-semantic=${{steps.versions.outputs.current_semantic}}"
          echo "next-semantic=${{steps.versions.outputs.next_semantic}}"
          echo "branch-semantic=${{steps.versions.outputs.branch_semantic}}"

      - name: Set the infra version
        id: infra_version
        shell: bash
        run: |
          if [ "${{ github.ref_type }}" == "branch" ]
          then
            echo "value=${{steps.versions.outputs.branch_semantic}}" >> $GITHUB_OUTPUT
          else
            echo "value=${{github.ref_name}}" >> $GITHUB_OUTPUT
          fi

      - name: terraform action
        uses: keeonline/github-actions/terraform-apply@karate
        env:
          TF_VAR_infra_environment: ${{inputs.environment}}
          TF_VAR_infra_version: ${{steps.infra_version.outputs.value}}
        with:
          aws_account_id: ${{secrets.AWS_ACCOUNT_ID}}
          aws_region: ${{secrets.AWS_REGION}}
          action: ${{inputs.action}}
          terraform_codedir: terraform
          environment: ${{inputs.environment}}
