name: Manage infrastructure

on:
  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: Terraform action
        required: true
        options:
          - apply-plan
          - apply
          - destroy-plan
          - destroy
        default: apply-plan
      environment:
        type: environment
        description: The targeted GitHub environment
        required: false
        default: test

jobs:
  manage-resources:
    name: Manage resources
    runs-on: ubuntu-24.04
    environment: ${{inputs.environment}}
    env:
      TF_VAR_environment: ${{inputs.environment}}
      TF_VAR_iac_version: v-carlos-fandango
      TF_VAR_infra_environment: ${{vars.INFRA_ENVIRONMENT}}
    permissions:
      contents: write
      id-token: write
    steps:
      - name: terraform action
        uses: keeonline/github-actions/show@main
        with:
          aws_account_id: ${{secrets.AWS_ACCOUNT_ID}}
          action: ${{inputs.action}}
          terraform_codedir: terraform/core
          environment: ${{inputs.environment}}
