name: Manage core infrastructure resources

on:
  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: Terraform action
        required: true
        options:
          - apply-plan
          - apply
          - destroy-plan
          - destroy
        default: apply-plan
      environment:
        type: environment
        description: The targeted GitHub environment
        required: false
        default: test

jobs:
  call-reusable-workflow:
    name: Reuseable manage resources ${{inputs.action}}
    uses: keeonline/github-workflows/.github/workflows/reusable-core.yml@v0.0.2
    with:
      action: ${{inputs.action}}
      environment: ${{inputs.environment}}
      iac_ref: ${{github.ref_name}}
    secrets: inherit
    permissions:
      contents: write
      id-token: write
