name: Manage infrastructure

on:
  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: Terraform action
        required: true
        options:
          - apply-plan
          - apply
          - destroy-plan
          - destroy
        default: apply-plan
      environment:
        type: environment
        description: The targeted GitHub environment
        required: false
        default: test

jobs:
  manage-resources:
    name: Manage resources
    uses: keeonline/github-workflows/.github/workflows/terraform-action.yml@v0.0.4
    with:
      action: ${{inputs.action}}
      repo_owner: ${{github.repository_owner}}
      repo_name: ${{github.event.repository.name}}
      work_dir: terraform/core
      environment: ${{inputs.environment}}
      iac_ref: ${{github.ref_name}}
    secrets: inherit
    permissions:
      contents: write
      id-token: write
name: Manage infrastructure

on:
  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: Terraform action
        required: true
        options:
          - apply-plan
          - apply
          - destroy-plan
          - destroy
        default: apply-plan
      environment:
        type: environment
        description: The targeted GitHub environment
        required: false
        default: test

jobs:
  manage-resources:
    name: Manage resources
    runs-on: ubuntu-24.04
    environment: ${{inputs.environment}}
    env:
      TF_VAR_infra_environment: ${{inputs.environment}}
      TF_VAR_infra_version: ${{github.ref_name}}
    permissions:
      contents: write
      id-token: write
    steps:
      - name: terraform action
        uses: keeonline/github-actions/terraform-action@v0.0.1
        with:
          aws_account_id: ${{secrets.AWS_ACCOUNT_ID}}
          aws_region: ${{secrets.AWS_REGION}}
          action: ${{inputs.action}}
          terraform_codedir: terraform/core
          environment: ${{inputs.environment}}
