name: Manage infrastructure

on:
  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: Terraform action
        required: true
        options:
          - apply-plan
          - apply
          - destroy-plan
          - destroy
        default: apply-plan
      environment:
        type: environment
        description: The targeted GitHub environment
        required: false
        default: test

jobs:
  manage-resources:
    name: Manage resources
    runs-on: ubuntu-24.04
    environment: ${{inputs.environment}}
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Get the artefact version
        id: artefact_version
        uses: keeonline/github-actions/artefact-version-by-ref-type@versions

      - name: show
        run: |
          echo "artefact_version=${{steps.artefact_version.outputs.version}}"

      - name: terraform action
        uses: keeonline/github-actions/terraform-action@versions
        env:
          TF_VAR_infra_environment: ${{inputs.environment}}
          TF_VAR_infra_version: ${{steps.artefact_version.outputs.version}}
        with:
          aws_account_id: ${{secrets.AWS_ACCOUNT_ID}}
          aws_region: ${{secrets.AWS_REGION}}
          action: ${{inputs.action}}
          terraform_codedir: terraform/core
          environment: ${{inputs.environment}}
