name: Infrastructure code push to main

on:
  push:
    branches:
      - main
        
jobs:
  tag-release:
      runs-on: ubuntu-24.04
      permissions:
        contents: write
      steps:
        - name: salutation
          run: |
            echo This is on_push for IaC. branch=${{ github.ref_name }}

        - name: Checkout sources
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Get the artefact version
          id: version
          uses: keeonline/github-actions/artefact-version@v0.0.4
            
        - name: Tag the repository with the semantic version
          uses: actions/github-script@v7
          with:
            script: |
              github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: 'refs/tags/${{steps.version.outputs.value}}',
                sha: context.sha
              })